# Generated by Django 5.0.4 on 2024-05-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_world_content_remove_world_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
